apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-frontend.fullname" . }}-secret
  labels:
    {{- include "todo-frontend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
